version: '3.1'

services:
  bot_app:
    container_name: bot_app
    restart: always
    working_dir: /usr/src/app
    env_file: .env
    build: .
    volumes:
      - .:/usr/src/app
    command: sh -c "python3 activity_bot/bot.py"
    depends_on:
      - database
#
  swagger:
    container_name: swagger
    restart: always
    working_dir: /usr/src/app
    env_file: .env
    build: .
    volumes:
      - .:/usr/src/app
    command: sh -c "python3 api/run.py"
    ports:
      - "8005:8005"

  database:
    container_name: postgres
    image: postgres:14.3-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
