version: '3.1'

services:
  bot_app:
    container_name: bot_app
    working_dir: /usr/src/app
    env_file: .env
    build: .
    volumes:
      - .:/usr/src/app
    command: sh -c "python3 activity_bot/bot.py"
    depends_on:
      - database

  database:
    container_name: postgres
    image: postgres:14.3-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
